---
title: "coevolution STERGM"
author: "Kirk Li"
date: "09/23/2014"
output:
  html_document:
    number_sections: yes
    toc: yes
---
# Coevolution STERGM
###############################################################################
```{r}

fls <-list.files("../../",recursive=T)
source(paste0("../../",fls[grep("kk_utils/utils.R",fls)]))
source(paste0("../../",fls[grep("cotergm/R/functions.R",fls)]))
fig.path = "figures/"
# .libPaths(cotergm)
library("statnet.common",lib=cotergm)
library("network",lib=cotergm)
library("ergm",lib=cotergm)
library("tergm",lib=cotergm)
set.seed(0)
```

```{r}
net1 <-as.network(read.table("../s50_data/s50-network1.dat"))
net2 <-as.network(read.table("../s50_data/s50-network2.dat"))
net3 <-as.network(read.table("../s50_data/s50-network3.dat"))
alcohol <- read.table("../s50_data/s50-alcohol.dat")
drugs <- read.table("../s50_data/s50-drugs.dat")
net <- net1

d2ud <- function(net){
	net <- as.matrix(net)
	for (i in 1:nrow(net)){
		for(j in 1:nrow(net)){
			net[i,j] = max(net[i,j],net[j,i])
		}}
	as.network(net,directed=FALSE)
}

net1 <- d2ud(net1)
net2 <- d2ud(net2)
net3 <- d2ud(net3)

al1 <- as.numeric(alcohol[,1]>3)+1
al2 <- as.numeric(alcohol[,2]>3)+1
net1 %v% "status" <- al1
net2 %v% "status" <- al2

y0 <- net1
nw <- net2
```




```{r}
# Formation Plus Network
FP <- FP.nw(y0,nw,"status")
# Formation Minus Network
FM <- FM.nw(y0,nw,"status")
# Dissolution Plus Network
DP <- DP.nw(y0,nw,"status")
# Dissolution Minus Network
DM <- DM.nw(y0,nw,"status")
```


```{r}
constraints=~atleastnonminus(y0)
MHproposal <- MHproposal(constraints,nw=y0,arguments=list())
summary(y0~edges+plus+nodematch_cotergm("status",diff=TRUE),MHproposal=MHproposal)
summary(nw~edges+plus+nodematch_cotergm("status",diff=TRUE),MHproposal=MHproposal)
summary(FP~edges+plus+nodematch_cotergm("status",diff=TRUE),MHproposal=MHproposal)
summary(FM~edges+plus+nodematch_cotergm("status",diff=TRUE),MHproposal=MHproposal)
summary(DP~edges+plus+nodematch_cotergm("status",diff=TRUE),MHproposal=MHproposal)
summary(DM~edges+plus+nodematch_cotergm("status",diff=TRUE),MHproposal=MHproposal)
summary(FP~edges+plus+nodematch_cotergm("status",diff=TRUE,y0edge=0),MHproposal=MHproposal)
summary(FP~edges+plus+nodematch_cotergm("status",diff=TRUE,y0edge=1),MHproposal=MHproposal)
```

```{r, warning=FALSE}
fit1 <- ergm(FP~edges+plus+nodematch_cotergm("status",diff=TRUE,y0edge=2),control=control.ergm(MCMC.burnin=10000,MCMC.samplesize=10000,MCMC.interval=100,MCMLE.maxit=20,MCMLE.min.effectiveSize=20,MCMC.max.interval=100), constraints=~atleastnonminus(y0),verbose=0)
fit1
mcmc.diagnostics(fit1, vars.per.page=5)

fit1.1 <- ergm(FP~edges+plus+nodematch_cotergm("status",diff=TRUE,y0edge=2,keep=1),control=control.ergm(MCMC.burnin=10000,MCMC.samplesize=10000,MCMC.interval=100,MCMLE.maxit=20,MCMLE.min.effectiveSize=20,MCMC.max.interval=100), constraints=~atleastnonminus(y0),verbose=0)
fit1.1
mcmc.diagnostics(fit1.1, vars.per.page=5)

fit1.2 <- ergm(FP~edges+plus+nodematch_cotergm("status",diff=TRUE,y0edge=2,keep=2),control=control.ergm(MCMC.burnin=10000,MCMC.samplesize=10000,MCMC.interval=100,MCMLE.maxit=20,MCMLE.min.effectiveSize=20,MCMC.max.interval=100), constraints=~atleastnonminus(y0),verbose=0)
fit1.2
mcmc.diagnostics(fit1.2, vars.per.page=5)
```

```{r, warning=FALSE}
fit2 <- ergm(FM~edges+plus+nodematch_cotergm("status",diff=TRUE,y0edge=2),control=control.ergm(MCMC.burnin=10000,MCMC.samplesize=10000,MCMC.interval=100,MCMLE.maxit=10,MCMLE.min.effectiveSize=20,MCMC.max.interval=100, MCMC.runtime.traceplot=T), constraints=~atleastnonplus(y0),verbose=1)

fit2
mcmc.diagnostics(fit2, vars.per.page=5)

fit2.1 <- ergm(FM~edges+plus+nodematch_cotergm("status",diff=TRUE,y0edge=2,keep=1),control=control.ergm(MCMC.burnin=10000,MCMC.samplesize=10000,MCMC.interval=100,MCMLE.maxit=20,MCMLE.min.effectiveSize=20,MCMC.max.interval=100), constraints=~atleastnonplus(y0),verbose=0)
fit2.1
mcmc.diagnostics(fit2.1, vars.per.page=5)

fit2.2 <- ergm(FM~edges+plus+nodematch_cotergm("status",diff=TRUE,y0edge=2,keep=2),control=control.ergm(MCMC.burnin=10000,MCMC.samplesize=10000,MCMC.interval=100,MCMLE.maxit=20,MCMLE.min.effectiveSize=20,MCMC.max.interval=100), constraints=~atleastnonplus(y0),verbose=0)
fit2.2
mcmc.diagnostics(fit2.2, vars.per.page=5)
```

```{r, warning=FALSE}
fit3 <- ergm(DP~edges+plus+nodematch_cotergm("status",diff=TRUE,y0nodal=2),control=control.ergm(MCMC.burnin=10000,MCMC.samplesize=10000,MCMC.interval=100,MCMLE.maxit=20,MCMLE.min.effectiveSize=20,MCMC.max.interval=100), constraints=~atmostnonminus(y0),verbose=0)
fit3
mcmc.diagnostics(fit3, vars.per.page=5)

fit3.1 <- ergm(DP~edges+plus+nodematch_cotergm("status",diff=TRUE,y0nodal=2,keep=1),control=control.ergm(MCMC.burnin=10000,MCMC.samplesize=10000,MCMC.interval=100,MCMLE.maxit=20,MCMLE.min.effectiveSize=20,MCMC.max.interval=100), constraints=~atmostnonminus(y0),verbose=0)
fit3.1
mcmc.diagnostics(fit3.1, vars.per.page=5)

fit3.2 <- ergm(DP~edges+plus+nodematch_cotergm("status",diff=TRUE,y0nodal=2,keep=2),control=control.ergm(MCMC.burnin=10000,MCMC.samplesize=10000,MCMC.interval=100,MCMLE.maxit=20,MCMLE.min.effectiveSize=20,MCMC.max.interval=100), constraints=~atmostnonminus(y0),verbose=0)
fit3.2
mcmc.diagnostics(fit3.2, vars.per.page=5)
```

```{r, warning=FALSE}
fit4 <- ergm(DM~edges+plus+nodematch_cotergm("status",diff=TRUE,y0nodal=2),control=control.ergm(MCMC.burnin=10000,MCMC.samplesize=10000,MCMC.interval=100,MCMLE.maxit=20,MCMLE.min.effectiveSize=20,MCMC.max.interval=100), constraints=~atmostnonplus(y0),verbose=0)
fit4
mcmc.diagnostics(fit4, vars.per.page=5)

fit4.1 <- ergm(DM~edges+plus+nodematch_cotergm("status",diff=TRUE,y0nodal=2,keep=1),control=control.ergm(MCMC.burnin=10000,MCMC.samplesize=10000,MCMC.interval=100,MCMLE.maxit=20,MCMLE.min.effectiveSize=20,MCMC.max.interval=100), constraints=~atmostnonplus(y0),verbose=0)
fit4.1
mcmc.diagnostics(fit4.1, vars.per.page=5)

fit4.2 <- ergm(DM~edges+plus+nodematch_cotergm("status",diff=TRUE,y0nodal=2,keep=2),control=control.ergm(MCMC.burnin=10000,MCMC.samplesize=10000,MCMC.interval=100,MCMLE.maxit=20,MCMLE.min.effectiveSize=20,MCMC.max.interval=100), constraints=~atmostnonplus(y0),verbose=0)
fit4.2
mcmc.diagnostics(fit4.2, vars.per.page=5)
```

```{r}
pvec <- c(round(summary(fit1)$coef[c("edges","plus","nodematch.status.1","nodematch.status.2"),4],2),round(summary(fit1.1)$coef[c("edges","plus","nodematch.status.1"),4],2),round(summary(fit1.2)$coef[c("edges","plus","nodematch.status.2"),4],2))

coefvec <- c(round(summary(fit1)$coef[c("edges","plus","nodematch.status.1","nodematch.status.2"),1],2),round(summary(fit1.1)$coef[c("edges","plus","nodematch.status.1"),1],2),round(summary(fit1.2)$coef[c("edges","plus","nodematch.status.2"),1],2))

# F+
M.fit1 <- matrix(paste0(coefvec,"(",pvec,")"),ncol=3,byrow=F)
rownames(M.fit1) <- c("edges","plus","--(SC)","++(SS)")
colnames(M.fit1) <- c("full","SC","SS")

pvec <- c(round(summary(fit2)$coef[c("edges","plus","nodematch.status.1","nodematch.status.2"),4],2),round(summary(fit2.1)$coef[c("edges","plus","nodematch.status.1"),4],2),round(summary(fit2.2)$coef[c("edges","plus","nodematch.status.2"),4],2))

coefvec <- c(round(summary(fit2)$coef[c("edges","plus","nodematch.status.1","nodematch.status.2"),1],2),round(summary(fit2.1)$coef[c("edges","plus","nodematch.status.1"),1],2),round(summary(fit2.2)$coef[c("edges","plus","nodematch.status.2"),1],2))

# F-
M.fit2 <- matrix(paste0(coefvec,"(",pvec,")"),ncol=3,byrow=F)
rownames(M.fit2) <- c("edges","plus","--(SS)","++(SC)")
colnames(M.fit2) <- c("full","SC","SS")

pvec <- c(round(summary(fit3)$coef[c("edges","plus","nodematch.status.1","nodematch.status.2"),4],2),round(summary(fit3.1)$coef[c("edges","plus","nodematch.status.1"),4],2),round(summary(fit3.2)$coef[c("edges","plus","nodematch.status.2"),4],2))

coefvec <- c(round(summary(fit3)$coef[c("edges","plus","nodematch.status.1","nodematch.status.2"),1],2),round(summary(fit3.1)$coef[c("edges","plus","nodematch.status.1"),1],2),round(summary(fit3.2)$coef[c("edges","plus","nodematch.status.2"),1],2))

# D+
M.fit3 <- matrix(paste0(coefvec,"(",pvec,")"),ncol=3,byrow=F)
rownames(M.fit3) <- c("edges","plus","--(SI)","++(SC)")
colnames(M.fit3) <- c("full","SC","SI")

pvec <- c(round(summary(fit4)$coef[c("edges","plus","nodematch.status.1","nodematch.status.2"),4],2),round(summary(fit4.1)$coef[c("edges","plus","nodematch.status.1"),4],2),round(summary(fit4.2)$coef[c("edges","plus","nodematch.status.2"),4],2))

coefvec <- c(round(summary(fit4)$coef[c("edges","plus","nodematch.status.1","nodematch.status.2"),1],2),round(summary(fit4.1)$coef[c("edges","plus","nodematch.status.1"),1],2),round(summary(fit4.2)$coef[c("edges","plus","nodematch.status.2"),1],2))

# D-
M.fit4 <- matrix(paste0(coefvec,"(",pvec,")"),ncol=3,byrow=F)
rownames(M.fit4) <- c("edges","plus","--(SC)","++(SI)")
colnames(M.fit4) <- c("full","SC","SI")
M.fit4[c(1,2,3,5,4),]


MM <- cbind(M.fit1[,1],M.fit2[,1],M.fit3[,1],M.fit4[,1])
rownames(MM)[c(4,5)] <- c("--","++")
colnames(MM) <-c("F+(++SS,--SC)","F-(--SS,++SC)","D+(--SI)","D-(++SI)")

```

```{r}
FP_fit <- M.fit1[c(1,2,3,5,4),]
FP_fit
```

```{r}
FM_fit <- M.fit2
FM_fit
```

```{r}
DP_fit <- M.fit3
DP_fit
```

```{r}
DM_fit <- M.fit4[c(1,2,3,5,4),]
DM_fit
```

```{r}
Combined_table <- MM
Combined_table
```




